// frontend/src/Page/Sidebar/sidebar.jsx
import React, { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { motion, easeOut } from "framer-motion";
import { House, NotebookText, Camera, ListChecks, Menu, X, LogOut } from "lucide-react";

export function Sidebar() {
  const navigate = useNavigate();
  const location = useLocation();
  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => setIsOpen(!isOpen);

  const handleLogout = () => {
    localStorage.removeItem("token"); 
    navigate("/login");
  };

  const menuItems = [
    { path: "/home", icon: <House size={20} />, label: "Home" },
    { path: "/jadwal", icon: <NotebookText size={20} />, label: "Buat Jadwal" },
    { path: "/dokumentasi", icon: <Camera size={20} />, label: "Dokumentasi" },
    { path: "/absen", icon: <ListChecks size={20} />, label: "Absensi" },
  ];

  return (
    <>
      <motion.aside
        initial={{ x: -200 }}
        animate={{ x: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="hidden md:flex flex-col justify-between w-64 h-screen bg-blue-500 text-white fixed left-0 top-0 shadow-2xl p-6"
      >
        <div>
          <div className="flex gap-4">
            <img src="/logo.png" className="w-10 h-10"></img>
            <h1 className="text-2xl font-bold mb-10 text-center">Ekskul Hub</h1>
          </div>

          <div className="flex flex-col gap-4">
            {menuItems.map((item, index) => {
              const isActive = location.pathname === item.path;
              return (
                <button
                  key={index}
                  onClick={() => navigate(item.path)}
                  className={`flex items-center gap-4 px-5 py-3 rounded-xl text-lg font-semibold transition-all duration-300 
                    ${isActive ? "bg-yellow-300 text-black" : "hover:bg-blue-600"}
                  `}
                >
                  {item.icon}
                  {item.label}
                </button>
              );
            })}
          </div>
        </div>

        <button
          onClick={handleLogout}
          className="flex items-center gap-3 px-5 py-3 rounded-xl text-lg font-semibold hover:bg-red-600 transition-all duration-300"
        >
          <LogOut size={20} />
          Logout
        </button>
      </motion.aside>

      <motion.div
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="pt-5 pb-5 px-4 flex justify-between items-center fixed top-0 left-0 w-full bg-blue-500 md:hidden shadow-md z-50"
      >
        <div className="flex gap-4">
          <img src="logo.png" className="w-10 h-10"></img>
          <h1 className="text-2xl font-bold text-white">Ekskul Hub</h1>
        </div>
        <button
          onClick={toggleMenu}
          className="text-white p-2"
          aria-label="Toggle Menu"
        >
          {isOpen ? <X size={32} /> : <Menu size={32} />}
        </button>

        {isOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-40 bg-blue-400/95 pt-20"
          >
            <motion.div
              initial={{ y: -50 }}
              animate={{ y: 0 }}
              transition={{ duration: 0.3, ease: easeOut }}
              className="flex flex-col gap-5 p-5"
            >
              {menuItems.map((item, index) => {
                const isActive = location.pathname === item.path;
                return (
                  <button
                    key={index}
                    onClick={() => {
                      navigate(item.path);
                      setIsOpen(false);
                    }}
                    className={`w-full text-xl font-semibold rounded-xl flex items-center justify-start gap-5 px-5 py-4 h-16 shadow-lg 
                      ${isActive ? "bg-yellow-300 text-black" : "text-white"}
                    `}
                  >
                    {item.icon}
                    {item.label}
                  </button>
                );
              })}

              <button
                onClick={() => {
                  handleLogout();
                  setIsOpen(false);
                }}
                className="w-full text-xl font-semibold rounded-xl flex items-center justify-start gap-5 px-5 py-4 h-16 shadow-lg text-white hover:bg-red-600"
              >
                <LogOut size={24} />
                Logout
              </button>
            </motion.div>
          </motion.div>
        )}
      </motion.div>
    </>
  );
}

// frontend/desktop/src/components/Sidebar/Sidebar.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { removeToken } from '../../utils/helper'

const router = useRouter()
const isOpen = ref(false)

const Handleopen = () => {
    isOpen.value = !isOpen.value
}

const LogOut = () => {
    removeToken(),
        router.push("/login")
}

</script>

<template>
    <!-- Large -->
    <div
        class="lg:flex hidden fixed top-0 left-0 h-screen bg-blue-600 flex-col h-screen w-1/6 justify-between pb-10 pt-10 gap-8 pl-2 pr-2">
        <div class="flex flex-col gap-10">
            <div class="flex items-center gap-2">
                <img src="/src/assets/logo.png" class="w-8">
                <h3 class="font-extrabold text-white text-2xl">Ekskul-Hub</h3>
            </div>
            <div class="flex flex-col gap-5">
                <router-link active-class="!text-black bg-yellow-300 text-black rounded-md"
                    class="text-white flex pl-4 py-3 items-center gap-3" to="/home">
                    <i class="pi pi-home text-lg font-semibold"></i>
                    <h3 class="font-semibold text-lg">Home</h3>
                </router-link>
                <router-link active-class="!text-black bg-yellow-300 text-black rounded-md"
                    class="text-white flex pl-4 py-3 items-center gap-3" to="/schedule">
                    <i class="pi pi-clipboard text-lg font-semibold"></i>
                    <h3 class="font-semibold text-lg">Buat Jadwal</h3>
                </router-link>
                <router-link active-class="!text-black bg-yellow-300 text-black rounded-md"
                    class="text-white flex pl-4 py-3 items-center gap-3" to="/dokumentasi">
                    <i class="pi pi-folder text-lg font-semibold"></i>
                    <h3 class="font-semibold text-lg">Dokumentasi</h3>
                </router-link>
                <router-link active-class="!text-black bg-yellow-300 text-black rounded-md"
                    class="text-white flex pl-4 py-3 items-center gap-3" to="/absen">
                    <i class="pi pi-list-check text-lg font-semibold"></i>
                    <h3 class="font-semibold text-lg">Absensi</h3>
                </router-link>
            </div>
        </div>
        <div class="flex gap-5 items-center justify-center">
            <i class="pi pi-sign-out text-white text-xl font-bold"></i>
            <button @click="LogOut">
                <h3 class="font-bold text-white text-xl">Logout</h3>
            </button>
        </div>
    </div>

    <!-- Small - Medium -->
    <div class="lg:hidden bg-blue-800 w-full py-2">
        <div class="flex justify-between">
            <div class="flex items-center pl-2 gap-3">
                <img src="/src/assets/logo.png" class="w-8">
                <h3 class=" text-white text-center font-bold">Ekskul-Hub</h3>
            </div>
            <button @click="Handleopen">
                <i class="text-white pi pi-list pr-5 font-bold text-2xl"></i>
            </button>
        </div>
        <div v-if="isOpen" class="mt-3 ml-5 mr-5 mb-2 flex flex-col gap-3">
            <div class="border-b w-full border-white"></div>
            <router-link active-class="bg-yellow-400 !text-black" class="text-white rounded-md py-2 flex justify-center"
                to="/home">
                <h3 class="font-bold">Home</h3>
            </router-link>
            <router-link active-class="bg-yellow-400 !text-black" class="text-white rounded-md py-2 flex justify-center"
                to="/schedule">
                <h3 class="font-bold">Jadwal</h3>
            </router-link>
            <router-link active-class="bg-yellow-400 !text-black" class="text-white rounded-md py-2 flex justify-center"
                to="/dokumentasi">
                <h3 class="font-bold">Dokumentasi</h3>
            </router-link>
            <router-link active-class="bg-yellow-400 !text-black" class="text-white rounded-md py-2 flex justify-center"
                to="/absen">
                <h3 class="font-bold">Absensi</h3>
            </router-link>
            <div class="flex gap-5 items-center justify-center">
                <i class="pi pi-sign-out text-white text-xl font-bold"></i>
                <button @click="LogOut">
                    <h3 class="font-bold text-white text-xl">Logout</h3>
                </button>
            </div>
        </div>
    </div>

</template>

<style scoped></style>
